#Query 2: Find the Semantic Trajectory with the Most Events

PREFIX sett: <http://purl.org/net/sett#>
PREFIX setKG: <http://purl.org/net/traces/knowledgegraph/setKG/>

SELECT ?trajectory (COUNT(?event) AS ?eventCount)
WHERE {
  ?trajectory a sett:SemanticTrajectory ;
              sett:hasEvent ?event .
}
GROUP BY ?trajectory
ORDER BY DESC(?eventCount)
#LIMIT 1


