# Query that shows correlation among the indices of the same commune

PREFIX setKG: <http://purl.org/net/traces/knowledgegraph/setKG/>
PREFIX sett: <http://purl.org/net/sett#>
PREFIX traces-geo: <http://purl.org/net/traces/dataset/geo/>

SELECT ?pointOfView ?episode ?episodeOrder ?abstractAnnotation ?domain
WHERE {
  traces-geo:FR74166 a sett:TerritorialUnit ;
                sett:hasMVT ?mvt .
  
  ?mvt sett:hasSemanticTrajectory ?semanticTrajectory .
  ?semanticTrajectory a sett:SemanticTrajectory ;
                      sett:hasPointOfView ?pointOfView ;
                      sett:hasEpisode ?episode .
  
  ?episode a sett:Episode ;
           sett:hasAnnotationEpisodeAbstract ?abstractAnnotation ;
           sett:hasAnnotationEpisodeDomain ?domain ;
           sett:hasEpisodeOrder ?episodeOrder .
  FILTER (?pointOfView = setKG:SnowPointOfView || ?pointOfView = setKG:VegetationPointOfView)
}
ORDER BY ?pointOfView ?episodeOrder

